package su.twomc.staffwork.storage;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import su.twomc.staffwork.model.StaffMember;
import su.twomc.staffwork.model.StatusInterval;
import su.twomc.staffwork.model.WorkSession;
import su.twomc.staffwork.model.WorkStatus;

public final class JdbcStaffRepository implements StaffRepository {
    private final DatabaseSettings settings;
    private HikariDataSource dataSource;

    public JdbcStaffRepository(DatabaseSettings settings) {
        this.settings = settings;
    }

    @Override
    public void initialize() {
        try {
            dataSource = new HikariDataSource(createConfig());
            migrate();
        } catch (RuntimeException exception) {
            close();
            throw new StorageException("Не удалось подключиться к базе данных", exception);
        }
    }

    private HikariConfig createConfig() {
        HikariConfig config = new HikariConfig();
        config.setPoolName("TMCStaffWork-Storage");
        config.setConnectionTimeout(settings.connectionTimeoutMs());
        config.setMaximumPoolSize(settings.type() == StorageType.SQLITE ? 1 : settings.maximumPoolSize());
        config.setJdbcUrl(jdbcUrl());
        if (settings.type() == StorageType.MYSQL) {
            config.setUsername(settings.username());
            config.setPassword(settings.password());
            config.addDataSourceProperty("cachePrepStmts", "true");
            config.addDataSourceProperty("prepStmtCacheSize", "250");
            config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
            config.addDataSourceProperty("useServerPrepStmts", "true");
            config.addDataSourceProperty("useUnicode", "true");
            config.addDataSourceProperty("characterEncoding", "utf8");
        }
        return config;
    }

    private String jdbcUrl() {
        Path directory = settings.dataDirectory().toAbsolutePath().normalize();
        return switch (settings.type()) {
            case SQLITE -> "jdbc:sqlite:" + directory.resolve("staffwork.db");
            case H2 -> "jdbc:h2:" + directory.resolve("staffwork").toString().replace('\\', '/');
            case MYSQL ->
                "jdbc:mysql://%s:%d/%s?useSSL=true&serverTimezone=UTC"
                        .formatted(settings.host(), settings.port(), validateDatabaseName(settings.database()));
            case YAML -> throw new IllegalArgumentException("YAML не является JDBC-хранилищем");
        };
    }

    private static String validateDatabaseName(String value) {
        if (value == null || !value.matches("[A-Za-z0-9_]{1,64}")) {
            throw new IllegalArgumentException("Некорректное имя базы данных");
        }
        return value;
    }

    private void migrate() {
        String identity =
                switch (settings.type()) {
                    case SQLITE -> "INTEGER PRIMARY KEY AUTOINCREMENT";
                    case H2 -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                    case MYSQL -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
                    case YAML -> throw new IllegalStateException("Недопустимый тип");
                };
        try (Connection connection = connection();
                Statement statement = connection.createStatement()) {
            connection.setAutoCommit(false);
            statement.execute(
                    "CREATE TABLE IF NOT EXISTS tmc_schema_history (version INTEGER PRIMARY KEY, applied_at BIGINT NOT NULL)");
            if (!hasMigration(connection, 1)) {
                statement.execute(
                        "CREATE TABLE IF NOT EXISTS tmc_staff ("
                                + "uuid VARCHAR(36) PRIMARY KEY, last_name VARCHAR(16) NOT NULL, rank_id VARCHAR(32) NOT NULL, "
                                + "enabled BOOLEAN NOT NULL, added_at BIGINT NOT NULL, added_by VARCHAR(36), last_seen_at BIGINT)");
                statement.execute("CREATE TABLE IF NOT EXISTS tmc_sessions (id "
                        + identity
                        + ", staff_uuid VARCHAR(36) NOT NULL, server_id VARCHAR(64) NOT NULL, "
                        + "started_at BIGINT NOT NULL, ended_at BIGINT, current_status VARCHAR(20) NOT NULL)");
                statement.execute("CREATE TABLE IF NOT EXISTS tmc_status_intervals ("
                        + "session_id BIGINT NOT NULL, sequence_no INTEGER NOT NULL, status VARCHAR(20) NOT NULL, "
                        + "started_at BIGINT NOT NULL, ended_at BIGINT, PRIMARY KEY(session_id, sequence_no))");
                createIndexIfMissing(connection, statement, "tmc_staff", "idx_tmc_staff_name", "last_name");
                createIndexIfMissing(
                        connection,
                        statement,
                        "tmc_sessions",
                        "idx_tmc_sessions_staff_time",
                        "staff_uuid, started_at, ended_at");
                createIndexIfMissing(
                        connection, statement, "tmc_sessions", "idx_tmc_sessions_active", "staff_uuid, ended_at");
                try (PreparedStatement insert = connection.prepareStatement(
                        "INSERT INTO tmc_schema_history(version, applied_at) VALUES(?, ?)")) {
                    insert.setInt(1, 1);
                    insert.setLong(2, Instant.now().toEpochMilli());
                    insert.executeUpdate();
                }
            }
            connection.commit();
        } catch (SQLException exception) {
            throw new StorageException("Не удалось применить миграцию схемы", exception);
        }
    }

    private static void createIndexIfMissing(
            Connection connection, Statement statement, String table, String index, String columns)
            throws SQLException {
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(null, null, table, false, false)) {
            while (indexes.next()) {
                if (index.equalsIgnoreCase(indexes.getString("INDEX_NAME"))) {
                    return;
                }
            }
        }
        statement.execute("CREATE INDEX " + index + " ON " + table + "(" + columns + ")");
    }

    private boolean hasMigration(Connection connection, int version) throws SQLException {
        try (PreparedStatement statement =
                connection.prepareStatement("SELECT version FROM tmc_schema_history WHERE version = ?")) {
            statement.setInt(1, version);
            try (ResultSet result = statement.executeQuery()) {
                return result.next();
            }
        }
    }

    @Override
    public Optional<StaffMember> findStaff(UUID uuid) {
        return findOne("SELECT * FROM tmc_staff WHERE uuid = ?", uuid.toString());
    }

    @Override
    public Optional<StaffMember> findStaffByName(String name) {
        return findOne("SELECT * FROM tmc_staff WHERE LOWER(last_name) = LOWER(?)", name);
    }

    private Optional<StaffMember> findOne(String sql, String value) {
        try (Connection connection = connection();
                PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, value);
            try (ResultSet result = statement.executeQuery()) {
                return result.next() ? Optional.of(readStaff(result)) : Optional.empty();
            }
        } catch (SQLException exception) {
            throw new StorageException("Не удалось прочитать сотрудника", exception);
        }
    }

    @Override
    public List<StaffMember> findAllStaff() {
        try (Connection connection = connection();
                PreparedStatement statement =
                        connection.prepareStatement("SELECT * FROM tmc_staff ORDER BY last_name");
                ResultSet result = statement.executeQuery()) {
            List<StaffMember> members = new ArrayList<>();
            while (result.next()) {
                members.add(readStaff(result));
            }
            return members;
        } catch (SQLException exception) {
            throw new StorageException("Не удалось прочитать список сотрудников", exception);
        }
    }

    @Override
    public void saveStaff(StaffMember member) {
        String update =
                "UPDATE tmc_staff SET last_name=?, rank_id=?, enabled=?, added_at=?, added_by=?, last_seen_at=? WHERE uuid=?";
        String insert =
                "INSERT INTO tmc_staff(uuid,last_name,rank_id,enabled,added_at,added_by,last_seen_at) VALUES(?,?,?,?,?,?,?)";
        try (Connection connection = connection();
                PreparedStatement statement = connection.prepareStatement(update)) {
            bindStaffUpdate(statement, member);
            if (statement.executeUpdate() == 0) {
                try (PreparedStatement create = connection.prepareStatement(insert)) {
                    bindStaffInsert(create, member);
                    create.executeUpdate();
                }
            }
        } catch (SQLException exception) {
            throw new StorageException("Не удалось сохранить сотрудника", exception);
        }
    }

    @Override
    public boolean deleteStaff(UUID uuid) {
        try (Connection connection = connection();
                PreparedStatement statement = connection.prepareStatement("DELETE FROM tmc_staff WHERE uuid=?")) {
            statement.setString(1, uuid.toString());
            return statement.executeUpdate() > 0;
        } catch (SQLException exception) {
            throw new StorageException("Не удалось удалить сотрудника", exception);
        }
    }

    @Override
    public Optional<WorkSession> findActiveSession(UUID uuid) {
        List<WorkSession> sessions = findSessionsWithSql(
                "SELECT * FROM tmc_sessions WHERE staff_uuid=? AND ended_at IS NULL ORDER BY started_at DESC",
                statement -> statement.setString(1, uuid.toString()));
        return sessions.stream().findFirst();
    }

    @Override
    public List<WorkSession> findSessions(UUID uuid, Instant from, Instant to) {
        return findSessionsWithSql(
                "SELECT * FROM tmc_sessions WHERE staff_uuid=? AND started_at < ? AND (ended_at IS NULL OR ended_at > ?) ORDER BY started_at",
                statement -> {
                    statement.setString(1, uuid.toString());
                    statement.setLong(2, to.toEpochMilli());
                    statement.setLong(3, from.toEpochMilli());
                });
    }

    @Override
    public WorkSession createSession(WorkSession session) {
        String sql =
                "INSERT INTO tmc_sessions(staff_uuid,server_id,started_at,ended_at,current_status) VALUES(?,?,?,?,?)";
        try (Connection connection = connection();
                PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            bindSession(statement, session);
            statement.executeUpdate();
            try (ResultSet keys = statement.getGeneratedKeys()) {
                if (!keys.next()) {
                    throw new StorageException("База данных не вернула идентификатор сессии");
                }
                WorkSession created = new WorkSession(
                        keys.getLong(1),
                        session.staffUuid(),
                        session.serverId(),
                        session.startedAt(),
                        session.endedAt(),
                        session.currentStatus(),
                        session.intervals());
                saveIntervals(connection, created);
                return created;
            }
        } catch (SQLException exception) {
            throw new StorageException("Не удалось открыть рабочую сессию", exception);
        }
    }

    @Override
    public void saveSession(WorkSession session) {
        try (Connection connection = connection()) {
            connection.setAutoCommit(false);
            try (PreparedStatement statement =
                    connection.prepareStatement("UPDATE tmc_sessions SET ended_at=?, current_status=? WHERE id=?")) {
                setInstant(statement, 1, session.endedAt());
                statement.setString(2, session.currentStatus().name());
                statement.setLong(3, session.id());
                if (statement.executeUpdate() != 1) {
                    throw new StorageException("Рабочая сессия не найдена");
                }
            }
            try (PreparedStatement delete =
                    connection.prepareStatement("DELETE FROM tmc_status_intervals WHERE session_id=?")) {
                delete.setLong(1, session.id());
                delete.executeUpdate();
            }
            saveIntervals(connection, session);
            connection.commit();
        } catch (SQLException exception) {
            throw new StorageException("Не удалось сохранить рабочую сессию", exception);
        }
    }

    @Override
    public List<WorkSession> findAllActiveSessions() {
        return findSessionsWithSql(
                "SELECT * FROM tmc_sessions WHERE ended_at IS NULL ORDER BY started_at", ignored -> {});
    }

    private List<WorkSession> findSessionsWithSql(String sql, SqlBinder binder) {
        try (Connection connection = connection();
                PreparedStatement statement = connection.prepareStatement(sql)) {
            binder.bind(statement);
            try (ResultSet result = statement.executeQuery()) {
                List<WorkSession> sessions = new ArrayList<>();
                while (result.next()) {
                    long id = result.getLong("id");
                    sessions.add(new WorkSession(
                            id,
                            UUID.fromString(result.getString("staff_uuid")),
                            result.getString("server_id"),
                            Instant.ofEpochMilli(result.getLong("started_at")),
                            nullableInstant(result, "ended_at"),
                            WorkStatus.valueOf(result.getString("current_status")),
                            readIntervals(connection, id)));
                }
                return sessions;
            }
        } catch (SQLException exception) {
            throw new StorageException("Не удалось прочитать рабочие сессии", exception);
        }
    }

    private List<StatusInterval> readIntervals(Connection connection, long sessionId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT * FROM tmc_status_intervals WHERE session_id=? ORDER BY sequence_no")) {
            statement.setLong(1, sessionId);
            try (ResultSet result = statement.executeQuery()) {
                List<StatusInterval> intervals = new ArrayList<>();
                while (result.next()) {
                    intervals.add(new StatusInterval(
                            WorkStatus.valueOf(result.getString("status")),
                            Instant.ofEpochMilli(result.getLong("started_at")),
                            nullableInstant(result, "ended_at")));
                }
                return intervals;
            }
        }
    }

    private void saveIntervals(Connection connection, WorkSession session) throws SQLException {
        String sql =
                "INSERT INTO tmc_status_intervals(session_id,sequence_no,status,started_at,ended_at) VALUES(?,?,?,?,?)";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (int index = 0; index < session.intervals().size(); index++) {
                StatusInterval interval = session.intervals().get(index);
                statement.setLong(1, session.id());
                statement.setInt(2, index);
                statement.setString(3, interval.status().name());
                statement.setLong(4, interval.startedAt().toEpochMilli());
                setInstant(statement, 5, interval.endedAt());
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }

    private static StaffMember readStaff(ResultSet result) throws SQLException {
        String addedBy = result.getString("added_by");
        return new StaffMember(
                UUID.fromString(result.getString("uuid")),
                result.getString("last_name"),
                result.getString("rank_id"),
                result.getBoolean("enabled"),
                Instant.ofEpochMilli(result.getLong("added_at")),
                addedBy == null ? null : UUID.fromString(addedBy),
                nullableInstant(result, "last_seen_at"));
    }

    private static void bindStaffUpdate(PreparedStatement statement, StaffMember member) throws SQLException {
        statement.setString(1, member.lastKnownName());
        statement.setString(2, member.rank());
        statement.setBoolean(3, member.enabled());
        statement.setLong(4, member.addedAt().toEpochMilli());
        statement.setString(
                5, member.addedBy() == null ? null : member.addedBy().toString());
        setInstant(statement, 6, member.lastSeenAt());
        statement.setString(7, member.uuid().toString());
    }

    private static void bindStaffInsert(PreparedStatement statement, StaffMember member) throws SQLException {
        statement.setString(1, member.uuid().toString());
        statement.setString(2, member.lastKnownName());
        statement.setString(3, member.rank());
        statement.setBoolean(4, member.enabled());
        statement.setLong(5, member.addedAt().toEpochMilli());
        statement.setString(
                6, member.addedBy() == null ? null : member.addedBy().toString());
        setInstant(statement, 7, member.lastSeenAt());
    }

    private static void bindSession(PreparedStatement statement, WorkSession session) throws SQLException {
        statement.setString(1, session.staffUuid().toString());
        statement.setString(2, session.serverId());
        statement.setLong(3, session.startedAt().toEpochMilli());
        setInstant(statement, 4, session.endedAt());
        statement.setString(5, session.currentStatus().name());
    }

    private static void setInstant(PreparedStatement statement, int index, Instant instant) throws SQLException {
        if (instant == null) {
            statement.setNull(index, java.sql.Types.BIGINT);
        } else {
            statement.setLong(index, instant.toEpochMilli());
        }
    }

    private static Instant nullableInstant(ResultSet result, String column) throws SQLException {
        long value = result.getLong(column);
        return result.wasNull() ? null : Instant.ofEpochMilli(value);
    }

    private Connection connection() throws SQLException {
        if (dataSource == null) {
            throw new SQLException("Хранилище ещё не инициализировано");
        }
        return dataSource.getConnection();
    }

    @Override
    public void close() {
        if (dataSource != null) {
            dataSource.close();
            dataSource = null;
        }
    }

    @FunctionalInterface
    private interface SqlBinder {
        void bind(PreparedStatement statement) throws SQLException;
    }
}
